/**
 * Programmatic SVG background tile.
 *
 * Icons: Font Awesome Free 6.7.2 — https://fontawesome.com
 * License: CC BY 4.0 — https://fontawesome.com/license/free
 * Copyright 2024 Fonticons, Inc.
 *
 * Layout: hand-placed — each icon has explicit cx/cy/rot/scale so the result
 * is fully deterministic and easy to tweak. Keep cx/cy ≥ 60 px from tile
 * edges so seams stay invisible when the tile repeats.
 */

import type { APIRoute } from 'astro';

interface Icon { w: number; h: number; path: string }

const ICONS: Record<string, Icon> = {
  beer: {
    w: 512, h: 512,
    path: 'M32 64c0-17.7 14.3-32 32-32l288 0c17.7 0 32 14.3 32 32l0 32 51.2 0c42.4 0 76.8 34.4 76.8 76.8l0 102.1c0 30.4-17.9 57.9-45.6 70.2L384 381.7l0 34.3c0 35.3-28.7 64-64 64L96 480c-35.3 0-64-28.7-64-64L32 64zM384 311.6l56.4-25.1c4.6-2.1 7.6-6.6 7.6-11.7l0-102.1c0-7.1-5.7-12.8-12.8-12.8L384 160l0 151.6zM160 144c0-8.8-7.2-16-16-16s-16 7.2-16 16l0 224c0 8.8 7.2 16 16 16s16-7.2 16-16l0-224zm64 0c0-8.8-7.2-16-16-16s-16 7.2-16 16l0 224c0 8.8 7.2 16 16 16s16-7.2 16-16l0-224zm64 0c0-8.8-7.2-16-16-16s-16 7.2-16 16l0 224c0 8.8 7.2 16 16 16s16-7.2 16-16l0-224z',
  },
  coffee: {
    w: 512, h: 512,
    path: 'M88 0C74.7 0 64 10.7 64 24c0 38.9 23.4 59.4 39.1 73.1l1.1 1C120.5 112.3 128 119.9 128 136c0 13.3 10.7 24 24 24s24-10.7 24-24c0-38.9-23.4-59.4-39.1-73.1l-1.1-1C119.5 47.7 112 40.1 112 24c0-13.3-10.7-24-24-24zM32 192c-17.7 0-32 14.3-32 32L0 416c0 53 43 96 96 96l192 0c53 0 96-43 96-96l16 0c61.9 0 112-50.1 112-112s-50.1-112-112-112l-48 0L32 192zm352 64l16 0c26.5 0 48 21.5 48 48s-21.5 48-48 48l-16 0 0-96zM224 24c0-13.3-10.7-24-24-24s-24 10.7-24 24c0 38.9 23.4 59.4 39.1 73.1l1.1 1C232.5 112.3 240 119.9 240 136c0 13.3 10.7 24 24 24s24-10.7 24-24c0-38.9-23.4-59.4-39.1-73.1l-1.1-1C231.5 47.7 224 40.1 224 24z',
  },
  runner: {
    w: 448, h: 512,
    path: 'M320 48a48 48 0 1 0 -96 0 48 48 0 1 0 96 0zM125.7 175.5c9.9-9.9 23.4-15.5 37.5-15.5c1.9 0 3.8 .1 5.6 .3L137.6 254c-9.3 28 1.7 58.8 26.8 74.5l86.2 53.9-25.4 88.8c-4.9 17 5 34.7 22 39.6s34.7-5 39.6-22l28.7-100.4c5.9-20.6-2.6-42.6-20.7-53.9L238 299l30.9-82.4 5.1 12.3C289 264.7 323.9 288 362.7 288l21.3 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-21.3 0c-12.9 0-24.6-7.8-29.5-19.7l-6.3-15c-14.6-35.1-44.1-61.9-80.5-73.1l-48.7-15c-11.1-3.4-22.7-5.2-34.4-5.2c-31 0-60.8 12.3-82.7 34.3L57.4 153.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l23.1-23.1zM91.2 352L32 352c-17.7 0-32 14.3-32 32s14.3 32 32 32l69.6 0c19 0 36.2-11.2 43.9-28.5L157 361.6l-9.5-6c-17.5-10.9-30.5-26.8-37.9-44.9L91.2 352z',
  },
  cloud: {
    w: 640, h: 512,
    path: 'M0 336c0 79.5 64.5 144 144 144l368 0c70.7 0 128-57.3 128-128c0-61.9-44-113.6-102.4-125.4c4.1-10.7 6.4-22.4 6.4-34.6c0-53-43-96-96-96c-19.7 0-38.1 6-53.3 16.2C367 64.2 315.3 32 256 32C167.6 32 96 103.6 96 192c0 2.7 .1 5.4 .2 8.1C40.2 219.8 0 273.2 0 336z',
  },
};

// ── Tile layout ───────────────────────────────────────────────────────────────
// cx/cy = icon centre in tile coords. Keep ≥ 60 px from all edges.
const TILE = 440;

interface Placement {
  icon:    keyof typeof ICONS;
  cx:      number;
  cy:      number;
  rot:     number;    // degrees
  scale:   number;
  opacity: number;
  color:   string;
}

const PLACEMENTS: Placement[] = [
  { icon: 'beer',   cx: 110, cy:  82, rot: -12, scale: 0.100, opacity: 0.28, color: '#E8C547' },
  { icon: 'cloud',  cx: 358, cy: 142, rot:   4, scale: 0.092, opacity: 0.22, color: '#F5D96A' },
  { icon: 'runner', cx:  87, cy: 353, rot:  -8, scale: 0.088, opacity: 0.30, color: '#C4A32A' },
  { icon: 'coffee', cx: 353, cy: 362, rot:  15, scale: 0.100, opacity: 0.25, color: '#E8C547' },
];

export const GET: APIRoute = () => {
  const groups = PLACEMENTS.map((p) => {
    const icon = ICONS[p.icon];
    return (
      `  <g transform="translate(${p.cx},${p.cy}) rotate(${p.rot}) scale(${p.scale}) translate(${-icon.w / 2},${-icon.h / 2})" ` +
      `fill="${p.color}" opacity="${p.opacity}">\n` +
      `    <path d="${icon.path}"/>\n` +
      `  </g>`
    );
  });

  const svg = [
    `<!--`,
    `  Icons: Font Awesome Free 6.7.2 — https://fontawesome.com`,
    `  License: CC BY 4.0 — https://fontawesome.com/license/free`,
    `  Copyright 2024 Fonticons, Inc.`,
    `  Generated by src/pages/bg-pattern.svg.ts`,
    `-->`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${TILE} ${TILE}" width="${TILE}" height="${TILE}">`,
    ...groups,
    `</svg>`,
  ].join('\n');

  return new Response(svg, {
    headers: { 'Content-Type': 'image/svg+xml' },
  });
};
